---
- name: Install updates on fileserver
  hosts: fileserver
  strategy: free
  tasks:
    - name: search and install updates
      win_updates:
        category_names:
          - CriticalUpdates
          - SecurityUpdates
          - CriticalUpdates
          - UpdateRollups
        reboot: yes
        reboot_timeout: 600
        log_path: c:\windows\logs\ansible_update_log.txt
      register: update_result
...
