---
- name: Upgrade Salt Minions
  hosts: all
  tasks:
    - win_shell: |
      cd c:\Downloads
      echo %CD%
      echo net stop salt-minion
      echo salt-minion service stopped
      ping -n 20 localhost -2 > NUL
      echo wait 20 secs
      echo install salt-minon
      echo Salt-Minion-3004.2-1-Py3-AMD64-Setup.exe /S /master=salt.ict.om.org /minion-name=%COMPUTERNAME% /move-config
      echo wait 60 secs
      ping -n 60 localhost -4 > NUL
      echo net start salt-minion
      args:
        executable: cmd

...
