---
- name: Upgrade Salt Minions
  hosts: all
  tasks:
    - win_shell: |
        cd c:\Downloads
        echo %CD%
        net stop salt-minion
        ping -n 20 localhost -2 > NUL
        .\Salt-Minion-3004.2-1-Py3-AMD64-Setup.exe /S /master=salt.ict.om.org /minion-name=$env:COMPUTERNAME /move-config
        ping -n 60 localhost -4 > NUL
        net start salt-minion
      args:
        executable: cmd

...
