---
# your own salt master needs to be entered below - else your minions will report to the master at salt.example.com
- name: Upgrade Salt Minions
  hosts: all
  tasks:
    - win_shell: |
        cd c:\Downloads
        echo %CD%
        net stop salt-minion
        ping -n 20 localhost -4 > empty
        & c:\Downloads\Salt-Minion-3004.2-1-Py3-AMD64-Setup.exe /S /master=salt.example.com /minion-name=$env:COMPUTERNAME /move-config
        ping -n 60 localhost -4 > empty
        net start salt-minion

...
