---
- name: Install all security, critical, and rollup updates with automatic reboots
  hosts: all
  win_updates:
    category_names:
    - SecurityUpdates
      - CriticalUpdates
      - UpdateRollups
    reboot: yes
...
